version: '3.2'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            ES_JAVA_OPTS: '-Xmx256m -Xms256m'
            ELASTIC_PASSWORD: changeme
            discovery.type: single-node
    tika:
        image: apache/tika:2.3.0
        ports:
            - '9998:9998'
